# **Объект Series**

In [3]:
import pandas as pd #импортируем библиотеку pandas
import numpy as np
from pandas import Series, DataFrame #импортируем объекты Series и DataFrame

*Series* — одномерный, похожий на массив объект, содержащий последовательность данных (типов, похожих на поддерживаемые NumPy) и ассоциированный с ним массив меток, который называется *индексом*. Простейший объект Series состоит только из массива данных:

In [4]:
obj = Series([4,7,-5,3]) #простейший способ задания объекта Series
obj

0    4
1    7
2   -5
3    3
dtype: int64

В строковом предтавлении Series, отображаемом в интерактивном режиме, индекс находится слева, а значения — справа. Имея объект Series, получить представление самого массива и его индекса можно с помощью атрибутов `values` и `index` соответственно:

In [ ]:
obj.values

array([ 4,  7, -5,  3])

In [ ]:
obj.index

RangeIndex(start=0, stop=4, step=1)

Имеет смысл создать объект Series с индексом, идентифицирующим каждый элемент данных:

In [ ]:
obj2 = Series([4,7,-5,3], index = ['d','b','a','c']) #создаем объект Series с заданными индексами
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [ ]:
obj2.values

array([ 4,  7, -5,  3])

In [ ]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

В отличие от массивов NumPy, для выборки одного или нескольких значений можно использовать метки в индексе:

In [ ]:
obj2['a']

-5

In [ ]:
obj2['d'] = 10
obj2

d    10
b     7
a    -5
c     3
dtype: int64

In [ ]:
obj2[['a','b','c']] #в данном случае [[a],[b],[c]] индетрпретируется как список индексов, хотя он содержит нецелые числа, а строки

a   -5
b    7
c    3
dtype: int64

Функции NumPy или похожие на них операции, например фильтрация с помощью булева массива, скалярное умножение или применение математических операций, сохраняют связь между индексом и значением:

In [ ]:
obj2[obj2 > 2]

d    10
b     7
c     3
dtype: int64

In [ ]:
obj2 * 2

d    20
b    14
a   -10
c     6
dtype: int64

In [ ]:
np.exp(obj2)

d    22026.465795
b     1096.633158
a        0.006738
c       20.085537
dtype: float64

Объект Series можно также представлять как упорядоченный словарь фиксированной длины, посколько он отображает индекс на данные. Его можно передавать многим функциям, ожидающим получить словарь:

In [ ]:
'd' in obj2

True

In [ ]:
30 in obj2

False

Если имеется словарь Python, содержащий данные, то из него можно создать объект Series:

In [ ]:
sdata = {'Ohio': 3500, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata) #создаем объект Series из словаря
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

Если передается только словарь, то в получившемся объекте Series ключи будут храниться в индексе по порядку:

In [ ]:
states = ['California','Ohio','Oregon','Texas']
obj4 = pd.Series (sdata, index = states)
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

В данном случае три значения, найденных в sdata, помещены в соответствующие им позиции, а для метки `'California'` никакого значения не нашлось, поэтому ей соответствует признак `NaN` (не число), которым в pandas обозначаются отсутствующие значения. Поскольку строки `'Utah'` не было в списке `states`, то ее нет и в результирующем объекте.

Для распознавания отсутствующих данных в pandas следует использовать функции`isnull` и `nitnull`:

In [ ]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [ ]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

У объекта Series есть также методы экземпляра:

In [ ]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

При выполнении арифметических операций объект Series автоматически выравнивает данные по индексной метке:

In [ ]:
obj3

Ohio       3500
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [ ]:
obj4

California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [ ]:
obj3+obj4

California         NaN
Ohio            7000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

И у самого объекта Series, и у его индекса имеется атрибут `name`, тесно связанный с другими частями функциональности pandas:

In [ ]:
obj4.name = 'population' #присваеваем объекту Series имя
obj4.index.name = 'state' #присваеваем название, общее всем индексам
obj4

state
California        NaN
Ohio           3500.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

Индекс объекта Series можно изменить на месте с помощью операции присваивания:

In [ ]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [ ]:
obj.index = ['Mom','Dad','Me','Sister']
obj

Mom       4
Dad       7
Me       -5
Sister    3
dtype: int64

Присваивать индексам можно не только значения списков, но и значения множеств и кортежей:

In [ ]:
obj.index = {1,2,3,4}
obj

1    4
2    7
3   -5
4    3
dtype: int64

In [ ]:
obj.index = (2,2,2,2)
obj

2    4
2    7
2   -5
2    3
dtype: int64

# **Объект DataFrame**

Объект DataFrame представляет собой табличную структуру данных, состоящую из упорядоченной коллекции столбцов, причем типы значений (числовой, строковый, булев и так далее) в разных столбцах могут различаться. В объекте DataFrame хранятся два индекса: по строкам и по столбцам. Можно считать, что это словарь объектов Series, имеющих общий индекс. Внутри объекта данные хранятся в виде одного или нескольких двумерных блоков, а не в виде списка, словаря или еще какой-нибудь коллекции одномерных массивов.

Есть много способов сконструировать объект DataFrame, один из самых распространенных — на основе словаря списков одинаковой длины или массивов NumPy:

In [ ]:
data = {'state': ['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],
        'year': [2000,2001,2002,2001,2002,2003],
        'population': [1.5,1.7,3.6,2.4,2.9,3.2]}
data

{'population': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2],
 'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2000, 2001, 2002, 2001, 2002, 2003]}

In [ ]:
frame = pd.DataFrame(data)
frame

    state  year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9
5  Nevada  2003         3.2

Для больших объектов DataFrame метод `head` отбирает только первые пять строк:

In [ ]:
frame.head()

    state  year  population
0    Ohio  2000         1.5
1    Ohio  2001         1.7
2    Ohio  2002         3.6
3  Nevada  2001         2.4
4  Nevada  2002         2.9

Если задать последовательность столбцов, то столбцы DataFrame расположатся строго в указанном порядке:

In [ ]:
pd.DataFrame(data, columns = ['year','state','population'])

   year   state  population
0  2000    Ohio         1.5
1  2001    Ohio         1.7
2  2002    Ohio         3.6
3  2001  Nevada         2.4
4  2002  Nevada         2.9
5  2003  Nevada         3.2

Если запросить столбец, которого нет в `data`, то он будет заполнен значениями `Nan`:

In [ ]:
frame2 = pd.DataFrame(data, columns = ['year','state','population','debt'],
                      index = [1,2,3,4,5,6])
frame2

   year   state  population debt
1  2000    Ohio         1.5  NaN
2  2001    Ohio         1.7  NaN
3  2002    Ohio         3.6  NaN
4  2001  Nevada         2.4  NaN
5  2002  Nevada         2.9  NaN
6  2003  Nevada         3.2  NaN

In [ ]:
frame2.columns #выдает список столбцов

Index(['year', 'state', 'population', 'debt'], dtype='object')

Столбец DataFrame можно извлечь как объект Series, воспользовавшись нотацией словарей или с помощью атрибута:

In [ ]:
frame2['state']

1      Ohio
2      Ohio
3      Ohio
4    Nevada
5    Nevada
6    Nevada
Name: state, dtype: object

In [ ]:
frame2.year

1    2000
2    2001
3    2002
4    2001
5    2002
6    2003
Name: year, dtype: int64

Синтаксис `frame_name[column]` работает для любого имени столбца, а `frame_name.column` — только когда имя столбца — допустимое для переменной Python.

Возвращенный объект Series имеет ТОТ ЖЕ индекс, что и DataFrame, а его атрибут `name` установлен соответствующим образом.

Строки также можно извлечь по позиции или по имени с помощью специального атрибута `loc`:

In [ ]:
frame2.loc[3] #в квадратных скобках задается индекс, к которому идет обращение

year          2002
state         Ohio
population     3.6
debt           NaN
Name: 3, dtype: object

Столбцы можно модифицировать путем присваивания. Например, пустому столбцу `'debt'` можно было бы присвоить скалярное значение или массив значений:

In [ ]:
frame2['debt'] = 16.5
frame2

   year   state  population  debt
1  2000    Ohio         1.5  16.5
2  2001    Ohio         1.7  16.5
3  2002    Ohio         3.6  16.5
4  2001  Nevada         2.4  16.5
5  2002  Nevada         2.9  16.5
6  2003  Nevada         3.2  16.5

In [ ]:
frame2['debt'] = np.array([1.5,2,3,4,5,6])
frame2

   year   state  population  debt
1  2000    Ohio         1.5   1.5
2  2001    Ohio         1.7   2.0
3  2002    Ohio         3.6   3.0
4  2001  Nevada         2.4   4.0
5  2002  Nevada         2.9   5.0
6  2003  Nevada         3.2   6.0

Когда столбцу присваивается список или массив, длина значения должна совпадать с длиной DataFrame. Если же присваивается объект Series, то его метки будут точно выровнены с индексом DataFrame, а в "дырки" будут вставлены значения `NaN`:

In [ ]:
val = pd.Series([-1.2,-1.5,-1.7], index = [2,4,5])
frame2['debt'] = val
frame2

   year   state  population  debt
1  2000    Ohio         1.5   NaN
2  2001    Ohio         1.7  -1.2
3  2002    Ohio         3.6   NaN
4  2001  Nevada         2.4  -1.5
5  2002  Nevada         2.9  -1.7
6  2003  Nevada         3.2   NaN

Присваивание несуществующему столбцу приводит к созданию нового столбца. Для удаления столбцов служит ключевое слово `del`, как и в обычном словаре.

Добавим новый столбец булевых признаков, показывающих, больше ли популяция штата `2.4`:

In [ ]:
frame2['big'] = frame2.population > 2.4
frame2

   year   state  population  debt    big
1  2000    Ohio         1.5   NaN  False
2  2001    Ohio         1.7  -1.2  False
3  2002    Ohio         3.6   NaN   True
4  2001  Nevada         2.4  -1.5  False
5  2002  Nevada         2.9  -1.7   True
6  2003  Nevada         3.2   NaN   True

Новый столбец нельзя создать, пользуясь синтаксисом `frame2.column_name`.

Удалим созданный столбец, используя `del`:

In [ ]:
del frame2['big']
frame2.columns

Index(['year', 'state', 'population', 'debt'], dtype='object')

Столбец, возвращаемый в ответ на запрос к DataFrame по индексу, является *представлением*, а не копией данных. Следовательно, любые модификации этого объекта Series найдут отражение и в DataFrame. Чтобы скопировать столбец, нужно выбрать метод `copy` объекта Series.

Еще одна распространенная форма данных — словарь словарей:

In [ ]:
pop = {'Nevada':{2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

Если передать вложенный словарь объекту DataFrame, то pandas интерпретирует ключи внешнего словаря как столбцы, а ключи внутреннего словаря — как индексы строк:

In [ ]:
frame3 = pd.DataFrame(pop)
frame3

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

Объект DataFrame можно транспонировать, как и для таблиц NumPy:

In [ ]:
frame3.T

        2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

Ключи внутренних словарей объединяются и сортируются для образования индекса результата. Однако этого не происходит, если индекс задан явно:

In [ ]:
DataFrame(pop, index = [2001, 2002, 2003])

      Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

Словари объектов Series интерпретируются сходным образом:

In [ ]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
DataFrame(pdata)

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

Если у объектов, возвращаемых при обращении к атрибутам `index` и `columns` объекта DataFrame, установлен атрибут `name`, то он также выводится:

In [ ]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

Как и в случае с Series, атрибут `values` возвращает данные, хранящиеся в DataFrame, в виде двумерного массива `ndarray`:

In [ ]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

Если у столбцов DataFrame разные типы данных, то `dtype` массива `values` будет выбран так, чтобы охватить все столбцы:

In [ ]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# **Индексные объекты**

В индексных объектах pandas хранятся метки вдоль осей и прочие метаданные. Любой массив или иная последовательность меток, указанная при конструировании Series или DataFrame, преобразуется в объект Index:

In [ ]:
obj = Series(range(3), index = ['a','b','c'])
index = obj.index
index

Index(['a', 'b', 'c'], dtype='object')

Индексные объекты *неизменяемы*, то есть их нельзя модифицировать.

Неизменяемость важна, для того чтобы несколько структур данных могли совместно использовать один и тот же индексный объект, не боясь его повредить:

In [ ]:
labels = pd.Index(np.arange(1,4))
labels

Int64Index([1, 2, 3], dtype='int64')

In [ ]:
obj2 = pd.Series([1.5,-2.5,0], index = labels)
obj2

1    1.5
2   -2.5
3    0.0
dtype: float64

In [ ]:
obj2.index is labels

True

Индексный объект не только похож на массив, но и ведет себя как множество фиксированного размера:

In [ ]:
frame3

state  Nevada  Ohio
year
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [ ]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

В отличие от множеств, индекс может содержать повторяющиеся метки:

In [ ]:
dup_labels = pd.Index(['foo','foo','bar','bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

Если при выборке указана повторяющаяся метка, то будут выбраны все элементы с такой меткой.

Основные свойства и методы для работы с индексами:

In [ ]:
append #конкатенирует с дополнительными индексными объектами, порождая новый объект Index
diff #вычисляет теоретико-множественную разность, представляя ее в виде индексного объекта
intersection #вычисляет теоретико-множественное пересечение
union #вычисляет теоретико-множественное объединение
isin #вычисляет булев массив, показывающий, содержится ли каждое значение индекса в переданной коллекции
delete #вычисляет новый индексный объект, получающийся после удаления элемента с индексом i
drop #вычисляет новый индексный объект, получающийся после удаления переданных значений
insert #вычисляет новый индексный объект, получающийся после вставки элемента в позицию с индексом i
is_monotonic #возвращает True, если каждый элемент больше предыдущего или равен ему
is_unique #возвращает True, если в индексе нет повторяющихся значений
unique #вычисляет массив уникальных значений в индексе

# **Базовая функциональность**

# **Переиндексация**

Для объектов pandas важен метод `reindex`, то есть возможность создания нового объекта, данные в котором *согласуются* с новым индексом. Например:

In [ ]:
obj = Series([4.5,7.2,-5.3,3.6], index = ['d','b','a','c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

Если вызвать `reindex` для этого объекта Series, то данные будут реорганизованы в соответствии с новым индексом, а если из каких-то имеющихся в этом индексе значений раньше не было, то вместо них будут подставлены отсутствующие значения:

In [ ]:
obj2 = obj.reindex(['a','b','c','d','e'])
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

Для упорядоченных данных, например, временных рядов, иногда желательно произвести интерполяцию, или восполнение, отсутствующих значений в процессе переиндексации. Это позволяет сделать параметр `method`; так, если задать для него значение `ffill`, то будет произведено прямое восполнение значений:

In [ ]:
obj3 = pd.Series(['blue','purple','yellow'], index = [0,2,4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [ ]:
obj3.reindex(range(6), method = 'ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

В случае объекта DataFrame функция `reindex` может изменять строки, столбцы или то и другое. Если ей передать просто последовательность, то в результирующем объекте переиндексируются строки:

In [ ]:
frame = pd.DataFrame(np.arange(9).reshape((3,3)),
                     index = ['a','c','d'],
                     columns = ['Ohio','Texas','California'])
frame

   Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [ ]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

   Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

Столбцы можно переиндексировать, задав ключевое слово `columns`:

In [ ]:
states = ['Texas','Utah','California']
frame.reindex(columns = states)

   Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

Аргументы функции `reindex`

In [ ]:
index# Последовательность, которая должна стать новым индексом. Может быть экземпляром Index или любой другой структурой данных Python, похожей на последовательность.
#Экземпляр Index будет использован как есть, без копирования
method# Метод интерполяции (восполнения), возможные значения приведены в табл. 5.4
fill_value# Значение, которое должно подставляться вместо отсутствующих значений, появляющихся в результате переиндексации
limit# При прямом или обратном восполнении максимальная длина восполняемой лакуны (выраженная числом элементов)
tolerance# При прямом или обратном восполнении максимальная длина восполняемой лакуны (выраженная абсолютным расстоянием)
level# Сопоставить с простым объектом Index на указанном уровне MultiIndex, иначе выбрать подмножество
copy# Не копировать данные, если новый индекс эквивалентен старому. По умолчанию True (т. е. всегда копировать данные)

NameError: ignored

# Удаление элементов из оси

Удалить один или несколько элементов из оси просто, если имеется ин-
дексный массив или список, не содержащий этих значений. Метод `drop` воз-
вращает новый объект, в котором указанные значения удалены из оси:

In [ ]:
obj = pd.Series(np.arange(5.), index = ['a','b','c','d','e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [ ]:
new_obj = obj.drop('c')
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [ ]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

В случае DataFrame указанные в индексе значения можно удалить из любой
оси. Для иллюстрации сначала создадим объект DataFrame:

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one','two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.drop(['Colorado', 'Ohio'])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

Чтобы удалить столбцы, следует передать axis=1 или axis='columns':

In [ ]:
data.drop('two', axis = 1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [ ]:
data.drop(['two', 'three'], axis = 'columns')

          one  four
Ohio        0     3
Colorado    4     7
Utah        8    11
New York   12    15

Многие функции, подобные `drop`, которые модифицируют размер или фор-
му Series или DataFrame, могут изменять объект на месте, не создавая новый
объект:

In [ ]:
obj.drop('c', inplace = True)
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

Будьте осторожны с режимом inplace, поскольку все удаленные в нем дан-
ные уничтожаются!!!

# Доступ по индексу, выборка и фильтрация

Доступ по индексу к объекту Series `(obj[...])` работает так же, как для массивов NumPy, с тем отличием, что индексами могут быть не только целые,
но и любые значения из индекса объекта Series. Вот несколько примеров:

In [ ]:
obj = pd.Series(np.arange(4.), index = ['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [ ]:
obj['b']

1.0

In [ ]:
obj[1]

1.0

In [ ]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [ ]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [ ]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [ ]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

Вырезание с помощью меток отличается от обычного вырезания в Python
тем, что конечная точка включается:

In [ ]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

Установка с помощью этих методов модифицирует соответствующий участок
Series:

In [ ]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

Обращение по индексу к DataFrame предназначено для получения одного
или нескольких столбцов путем задания одного значения или последователь-
ности:

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [ ]:
data[['three', 'one']]

          three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

У доступа по индексу есть несколько частных случаев. Во-первых, выборка
или вырезание данных с помощью булева массива:

In [ ]:
data[:2]

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [ ]:
data[data['three']>5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

Для удобства предоставляется специальный синтаксис выборки строк `data[:2]`. Если передать один элемент или список оператору `[]`, то выбираются
столбцы.

Еще одна возможность – доступ по индексу с помощью булева DataFrame,
например, порожденного в результате скалярного сравнения:

In [ ]:
data<5

            one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [ ]:
data[data<5]=0
data

          one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Выборка с помощью loc и iloc

Для доступа к строкам DataFrame по индексу с помощью меток я ввел
специальные индексные операторы `loc` и `iloc`. Они позволяют выбрать под-
множество строк и столбцов DataFrame с применением нотации NumPy, используя либо метки строк (*loc*), либо целые числа (`iloc`).

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns = ['one', 'two', 'three', 'four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [ ]:
data.loc['Colorado', ['two','three']]

two      5
three    6
Name: Colorado, dtype: int64

Затем произведем аналогичную выборку, но уже по целочисленным ин-
дексам:

In [ ]:
data.iloc[2,[3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int64

In [ ]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [ ]:
data.iloc[[0,2],[3,0,1]]

      four  one  two
Ohio     0    0    0
Utah    11    8    9

Обе функции индексирования работают не только с одиночными метками
или списками меток, но и со срезами:

In [ ]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [ ]:
data.iloc[:, :3][data.three > 5]

          one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [ ]:
df[val]# Выбрать один столбец или последовательность столбцов из DataFrame.
#Частные случаи: булев массив (фильтрация строк), срез (вырезание
#строк) или булев DataFrame (установка значений в позициях,
#удовлетворяющих некоторому критерию)
df.loc[val] #Выбрать одну строку или подмножество строк из DataFrame по метке
obj.loc[:, val]# Выбрать один столбец или подмножество столбцов по метке
df.iloc[val1, val2] #Выбрать строки и столбцы по метке
df.iloc[where]# Выбрать одну строку или подмножество строк из DataFrame по целочисленной позиции
obj.iloc[:, where]# Выбрать один столбец или подмножество столбцов по целочисленной позиции
df.loc[where_i, where_j]# Выбрать строки и столбцы по целочисленной позиции
df.at[label_i, label_j]# Выбрать одно скалярное значение по меткам строки и столбца
df.iat[label_i, label_j]# Выбрать одно скалярное значение по целочисленным позициям строки и столбца метод reindex Выбрать строки или столбцы по меткам 
#методы get_value, set_value Выбрать одно значение по меткам строки и столбца

# Целочисленные индексы

Чтобы не оставлять место двусмысленности, в случае когда индекс по не-
которой оси содержит целые числа, выборка данных всегда производится по
метке. А чтобы точно выразить свои намерения, используйте метод loc (для
доступа по метке) или iloc (для доступа по позиции)

# Арифметические операции и выравнивание данных

Одна из самых важных черт pandas – поведение арифметических операций для объектов с разными индексами. Если при сложении двух объектов
обнаруживаются различные пары индексов, то результирующий индекс будет
объединением индексов. Для тех, кто имеет опыт работы с базами данных,
отметим, что это аналог внешнего соединения по индексным меткам. Рассмотрим простой пример:

In [ ]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [ ]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [ ]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [ ]:
s1+s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

Вследствие внутреннего выравнивания данных образуются отсутствующие
значения в позициях, для которых не нашлось соответственной пары. Отсут-
ствующие значения распространяются на последующие операции.
В случае DataFrame выравнивание производится как для строк, так и для
столбцов:

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [ ]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [ ]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [ ]:
df1+df2

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

Поскольку столбцы 'c' и 'e' не встречаются в обоих объектах DataFrame
сразу, то в результирующем объекте они помечены как отсутствующие. То
же самое относится к меткам строк, не встречающимся в обоих объектах.
Если сложить объекты DataFrame, не имеющие общих столбцов и строк, то
результат будет содержать только значения NaN.

In [ ]:
df1 = pd.DataFrame({'A': [3, 5]})
df2 = pd.DataFrame({'B': [3, 4]})

In [ ]:
df1-df2

    A   B
0 NaN NaN
1 NaN NaN

# Восполнение значений в арифметических методах

При выполнении арифметических операций с объектами, проиндексиро-
ванными по-разному, иногда желательно поместить специальное значение,
например 0, в позицию операнда, которым в другом операнде соответствует
отсутствующая позиция:

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series

In [ ]:
df1 = DataFrame(np.arange(12).reshape((3,4)),
                columns = list('abcd'))
df2= DataFrame(np.arange(20).reshape((4,5)),
                columns = list('abcde'))

In [ ]:
df1

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [ ]:
df2

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [ ]:
df1+df2

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [ ]:
df1.add(df2, fill_value=0)# Увеличиваем df1 до размеров df2 заполняя нулями

      a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

У арифметическиих методов имеется вариант, начинающийся буквой r,
в котором аргументы поменяли местами. Поэтому следующие два предло-
жения эквивалентны:

In [ ]:
1 / df1

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [ ]:
df1.rdiv(1)

       a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

Точно так же, выполняя переиндексацию объекта Series или DataFrame,
можно указать восполняемое значение:

In [ ]:
df1.reindex(columns=df2.columns, fill_value = 0)

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

**Гибкие арифметические методы**

In [ ]:
add, radd# Сложение (+)
sub, rsub# Вычитание (-)
div, rdiv# Деление (/)
floordiv, rfloordiv# Деление с отсечением (//)
mul, rmul# Умножение (*)
pow, rpow# Возведение в степень (**)

# Операции между DataFrame и Series

Как и в случае массивов NumPy, арифметические операции между DataFrame
и Series корректно определены. В качестве пояснительного примера
рассмотрим вычисление разности между двумерным массивом и одной из
его строк:

In [ ]:
arr = np.arange(12).reshape((3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr[0]

array([0, 1, 2, 3])

In [ ]:
arr-arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

Когда мы вычитаем `arr[0]` из `arr`, операция производится один раз для
каждой строки. Это называется укладыванием и подробно объясняется в при-
ложении A, поскольку имеет отношение к массивам NumPy вообще. Операции
между DataFrame и Series аналогичны:

In [ ]:
frame = DataFrame(np.arange(12).reshape((4,3)),
                  columns = list('bde'),
                  index = ['utah', 'Ohio', 'Texas', 'Oregon'])
frame

        b   d   e
utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

In [ ]:
series = frame.iloc[0]
series

b    0
d    1
e    2
Name: utah, dtype: int64

In [ ]:
frame-series

        b  d  e
utah    0  0  0
Ohio    3  3  3
Texas   6  6  6
Oregon  9  9  9

Если какой-нибудь индекс не найден либо в столбцах DataFrame, либо в ин-
дексе Series, то объекты переиндексируются для образования объединения:

In [ ]:
series2 = Series(np.arange(3), index = ['b', 'e', 'f'])
frame+series2

          b   d     e   f
utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

Если вы хотите вместо этого сопоставлять строки, а укладывать столбцы,
то должны будете воспользоваться каким-нибудь арифметическим методом.
Например:

In [ ]:
series3 = frame['d']
series3
frame.sub(series3, axis = 'index')

        b  d  e
utah   -1  0  1
Ohio   -1  0  1
Texas  -1  0  1
Oregon -1  0  1

Передаваемый номер оси – это ось, вдоль которой производится сопостав-
ление. В данном случае мы хотим сопоставлять с индексом строк DataFrame
(`axis='index'` или `axis=0`) и укладывать поперек.

# Применение функций и отображение

Универсальные функции NumPy (поэлементные методы массивов) отлично
работают и с объектами pandas:

In [ ]:
frame

        b   d   e
utah    0   1   2
Ohio    3   4   5
Texas   6   7   8
Oregon  9  10  11

Еще одна часто встречающаяся операция – применение функции, опреде-
ленной для одномерных массивов, к каждому столбцу или строке. Именно
это и делает метод `apply` объекта DataFrame:

In [ ]:
f = lambda x: x.max() - x.min()
frame.apply(f)

b    9
d    9
e    9
dtype: int64

Можно использовать и поэлементные функции Python. Допустим, требу-
ется вычислить форматированную строку для каждого элемента `frame` с плавающейточкой. Это позволяет сделать метод `applymap`:

In [ ]:
format = lambda x: '%.2f' % x
frame.applymap(format)

           b      d      e
utah    0.00   1.00   2.00
Ohio    3.00   4.00   5.00
Texas   6.00   7.00   8.00
Oregon  9.00  10.00  11.00

Этот метод называется `applymap`, потому что в классе `Series` есть метод map
для применения функции к каждому элементу:

In [ ]:
frame['e'].map(format)

utah       2.00
Ohio       5.00
Texas      8.00
Oregon    11.00
Name: e, dtype: object

# Сортировка и ранжирование

Сортировка набора данных по некоторому критерию – еще одна важная
встроенная операция. Для лексикографической сортировки по индексу служит метод `sort_index`, который возвращает новый отсортированный объект:

In [ ]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
obj = Series(range(4), index = ['d', 'a', 'b', 'c'])
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

В случае DataFrame можно сортировать по индексу, ассоциированному
с любой осью:

In [ ]:
frame = DataFrame(np.arange(8).reshape((2,4)),
                  index = ['three', 'one'],
                  columns = list('dabc'))
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [ ]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [ ]:
frame.sort_index(axis = 1)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

По умолчанию данные сортируются в порядке возрастания, но можно от-
сортировать их и в порядке убывания:

In [ ]:
frame.sort_index(axis = 1, ascending =  False)

       d  c  b  a
three  0  3  2  1
one    4  7  6  5

Для сортировки Series по значениям служит метод sort_values:

In [ ]:
series = Series([-4, 5, 6, 1])
series.sort_values()

0   -4
3    1
1    5
2    6
dtype: int64

Отсутствующие значения по умолчанию оказываются в конце Series:

In [ ]:
obj = Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

Объект DataFrame можно сортировать по значениям в одном или несколь-
ких столбцах. Для этого имена столбцов следует передать в качестве значения
параметра by метода sort_values:

In [ ]:
frame = DataFrame({'b' : [4, 4, 4, 7, 3, 2], 'a': [-1, 2, -2, 2, 8, 5]})
frame

   b  a
0  4 -1
1  4  2
2  4 -2
3  7  2
4  3  8
5  2  5

In [ ]:
frame.sort_values(by = 'b')

   b  a
5  2  5
4  3  8
0  4 -1
1  4  2
2  4 -2
3  7  2

Для сортировки по нескольким столбцам следует передать список имен:

In [ ]:
frame.sort_values(by = ['a', 'b'])

   b  a
2  4 -2
0  4 -1
1  4  2
3  7  2
5  2  5
4  3  8

*Ранжирование* заключается в присваивании рангов – от единицы до числа
присутствующих в массиве элементов. Для ранжирования применяется ме-
тод `rank` объектов Series и DataFrame; по умолчанию `rank` обрабатывает свя-
занные ранги, присваивая каждой группе средний ранг:

In [ ]:
obj = Series([7, -5, 7, 4, 2, 0, 4])
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

Ранги можно также присваивать в соответствии с порядком появления
в данных:

In [ ]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

Здесь элементам 0 и 2 присвоен не средний ранг 6.5, а ранг 6 и 7, потому
что в данных метка 0 предшествует метке 2.

Можно ранжировать и в порядке убывания:

In [ ]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

Способы обработки связанных рангов

In [ ]:
'average'# По умолчанию: одинаковым значениям присвоить средний ранг
'min'# Всем элементам группы присвоить минимальный ранг
'max'# Всем элементам группы присвоить максимальный ранг
'first'# Присваивать ранги в порядке появления значений в наборе данных
'dense'# Как method='min', но при переходе к следующей группе элементов
#  с одинаковым ранг всегда увеличивается на 1, а не на количество элементов в группе

DataFrame умеет вычислять ранги как по строкам, так и по столбцам:

In [ ]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1], 'c': [-2, 5, 8, -2.5]})
frame

     b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [ ]:
frame.rank(axis='columns')

     b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Индексы по осям с повторяющимися значениями

Рассмотрим
небольшой объект Series с повторяющимися значениями в индексе:

In [1]:
import numpy as np
import pandas as pd

In [3]:
obj = pd.Series(range(5), index = list('aabbc'))

In [4]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

О том, являются значения уникальными или нет, можно узнать, опросив
свойство `is_unique`:

In [5]:
obj.index.is_unique

False

Выборка данных – одна из основных операций, поведение которых меня-
ется в зависимости от наличия или отсутствия дубликатов. При доступе по
индексу, встречающемуся несколько раз, возвращается объект Series, если же
индекс одиночный, то скалярное значение:

In [6]:
obj['a']

a    0
a    1
dtype: int64

In [7]:
obj['c']

4

Это иногда усложняет код, поскольку тип, получающийся в результате ин-
дексирования, может зависеть от того, повторяется метка или нет.
Такое же правило действует и для доступа к строкам в DataFrame:

In [9]:
df = pd.DataFrame(np.random.randn(4,3), index = list('aabb'), columns = ['Ohio', 'Texas', 'New_York'])
df

       Ohio     Texas  New_York
a  0.422098 -1.324414  0.420381
a  0.864764  2.219035  0.444148
b -0.210732  0.191821  0.873353
b -1.682264  2.002577 -0.723444

In [11]:
df.loc['b']

       Ohio     Texas  New_York
b -0.210732  0.191821  0.873353
b -1.682264  2.002577 -0.723444